
import React, { useState } from 'react';
import { Globe, Terminal, Send, Search, Filter, Play, Clock, Code, ChevronRight, CheckCircle2, XCircle, Settings2, ArrowRightLeft, Database, Zap, Share2, ClipboardList, RefreshCw } from 'lucide-react';
import Card from './Shared/Card';

const Postbacks: React.FC = () => {
  const [activeTab, setActiveTab] = useState('relay');

  const incomingParameters = [
    { key: 'click_id', label: 'Internal Click ID', required: true, desc: 'The unique alphanumeric ID generated by our system for the session.' },
    { key: 'transaction_id', label: 'Advertiser Reference', required: false, desc: 'The unique ID sent back by the advertiser to confirm the lead.' },
    { key: 'payout', label: 'Dynamic Revenue', required: false, desc: 'The dollar amount received from the advertiser for this event.' },
  ];

  const outgoingMacros = [
    { macro: '{click_id}', desc: 'Relays the original system click identifier.' },
    { macro: '{sub1}', desc: 'Relays the value passed by affiliate in sub1 parameter.' },
    { macro: '{payout}', desc: 'Relays the calculated affiliate commission amount.' },
    { macro: '{offer_id}', desc: 'Relays the numeric ID of the converted inventory.' },
  ];

  return (
    <div className="space-y-6 animate-in fade-in duration-500">
      <div className="flex justify-between items-center">
         <div>
            <h1 className="text-2xl font-black uppercase tracking-tight text-gray-100">S2S Intelligence Hub</h1>
            <p className="text-sm text-gray-500 font-medium italic">"Managing L o G i c P u l s e™ server-to-server signals and parameter mapping logic."</p>
         </div>
      </div>
      
      <div className="flex gap-4 border-b border-gray-800 overflow-x-auto no-scrollbar">
        {[
          { id: 'relay', label: 'Relay Flow', icon: <Share2 size={16}/> },
          { id: 'parameters', label: 'Parameter Mapping', icon: <Settings2 size={16}/> },
          { id: 'affiliate-setup', label: 'Partner Config', icon: <ClipboardList size={16}/> },
          { id: 'logs', label: 'Signal History', icon: <Terminal size={16}/> },
        ].map(tab => (
          <button
            key={tab.id}
            onClick={() => setActiveTab(tab.id)}
            className={`px-6 py-4 text-xs font-black uppercase tracking-widest flex items-center gap-2 border-b-2 transition-all whitespace-nowrap ${
              activeTab === tab.id ? 'border-blue-500 text-blue-400 bg-blue-500/5' : 'border-transparent text-gray-500 hover:text-gray-300'
            }`}
          >
            {tab.icon} {tab.label}
          </button>
        ))}
      </div>

      <div className="animate-in fade-in slide-in-from-bottom-2 duration-500">
        {activeTab === 'relay' && (
          <div className="space-y-6">
             <Card title="Server-to-Server Data Lifecycle Visualizer">
                <div className="flex flex-col md:flex-row items-center justify-between gap-8 py-10 px-4">
                   {/* ADVERTISER SOURCE */}
                   <div className="flex-1 w-full max-w-[280px]">
                      <div className="bg-gray-950 border border-gray-800 rounded-2xl p-6 text-center shadow-inner relative group">
                         <div className="absolute -top-3 left-1/2 -translate-x-1/2 bg-indigo-600 px-3 py-1 rounded-full text-[8px] font-black uppercase tracking-widest text-white shadow-lg">Advertiser Signal</div>
                         <div className="p-4 bg-gray-900 rounded-xl mb-4 border border-gray-800 text-indigo-400"><Database size={32} className="mx-auto"/></div>
                         <h4 className="text-[11px] font-black text-gray-200 uppercase tracking-tight mb-2">Step 1: Inbound</h4>
                         <p className="text-[10px] text-gray-500 leading-relaxed uppercase tracking-tight">Receiving <code>click_id</code> and <code>amount</code> from advertiser endpoint.</p>
                      </div>
                   </div>

                   <ArrowRightLeft className="text-gray-700 md:rotate-0 rotate-90" size={32}/>

                   {/* PLATFORM ENGINE */}
                   <div className="flex-1 w-full max-w-[280px]">
                      <div className="bg-blue-600/5 border-2 border-blue-500/30 rounded-2xl p-6 text-center shadow-2xl relative overflow-hidden group">
                         <div className="absolute top-0 left-0 w-full h-1 bg-gradient-to-r from-blue-500 to-indigo-500"></div>
                         <div className="p-4 bg-gray-900 rounded-xl mb-4 border border-gray-800 text-blue-400"><Zap size={32} className="mx-auto animate-pulse"/></div>
                         <h4 className="text-[11px] font-black text-blue-400 uppercase tracking-tight mb-2">Step 2: Processing</h4>
                         <p className="text-[10px] text-gray-500 leading-relaxed uppercase tracking-tight italic">Validating conversion, calculating payout, and storing in global ledger.</p>
                      </div>
                   </div>

                   <ArrowRightLeft className="text-gray-700 md:rotate-0 rotate-90" size={32}/>

                   {/* AFFILIATE TARGET */}
                   <div className="flex-1 w-full max-w-[280px]">
                      <div className="bg-gray-950 border border-gray-800 rounded-2xl p-6 text-center shadow-inner relative group">
                         <div className="absolute -top-3 left-1/2 -translate-x-1/2 bg-green-600 px-3 py-1 rounded-full text-[8px] font-black uppercase tracking-widest text-white shadow-lg">Affiliate Relay</div>
                         <div className="p-4 bg-gray-900 rounded-xl mb-4 border border-gray-800 text-green-500"><Globe size={32} className="mx-auto"/></div>
                         <h4 className="text-[11px] font-black text-gray-200 uppercase tracking-tight mb-2">Step 3: Outbound</h4>
                         <p className="text-[10px] text-gray-500 leading-relaxed uppercase tracking-tight">Triggering partner postback URL with mapped macros (e.g. <code>{'{click_id}'}</code>).</p>
                      </div>
                   </div>
                </div>
             </Card>
          </div>
        )}

        {activeTab === 'parameters' && (
           <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
              <Card title="Advertiser Postback URL (Inbound)">
                 <div className="space-y-6">
                    <p className="text-[11px] text-gray-500 font-bold uppercase tracking-widest italic">"Provide this URL to your advertiser to track conversions back to our system."</p>
                    <div className="p-4 bg-gray-950 border border-blue-500/30 rounded-xl font-mono text-[10px] text-blue-400 break-all select-all shadow-inner">
                       https://track.logicpulse.io/pb?click_id={'{ADVERTISER_MACRO}'}&txid={'{ADVERTISER_MACRO}'}&rev={'{ADVERTISER_MACRO}'}
                    </div>
                    <div className="space-y-4 pt-4 border-t border-gray-800">
                       <label className="text-[10px] font-black text-gray-400 uppercase tracking-widest">Required Incoming Parameters</label>
                       {incomingParameters.map(p => (
                         <div key={p.key} className="flex justify-between items-start p-3 bg-gray-900 rounded-xl border border-gray-800">
                            <div>
                               <p className="text-xs font-black text-gray-200 uppercase tracking-tight">{p.key} <span className="text-gray-600">({p.label})</span></p>
                               <p className="text-[9px] text-gray-500 mt-1 uppercase font-bold italic">{p.desc}</p>
                            </div>
                            {p.required && <span className="text-[8px] font-black text-red-500 uppercase bg-red-500/10 px-1.5 py-0.5 rounded">Required</span>}
                         </div>
                       ))}
                    </div>
                 </div>
              </Card>

              <Card title="System Macros (Outbound Relay)">
                 <div className="space-y-6">
                    <p className="text-[11px] text-gray-500 font-bold uppercase tracking-widest italic">"Use these tokens in affiliate postback URLs to relay conversion data."</p>
                    <div className="grid grid-cols-1 gap-2">
                       {outgoingMacros.map(m => (
                         <div key={m.macro} className="flex items-center justify-between p-4 bg-gray-900 border border-gray-800 rounded-xl group hover:border-blue-500/30 transition-all">
                            <code className="text-blue-400 font-black font-mono text-sm">{m.macro}</code>
                            <span className="text-[10px] text-gray-500 font-black uppercase tracking-widest italic">{m.desc}</span>
                         </div>
                       ))}
                    </div>
                    <div className="p-4 bg-blue-600/5 border border-blue-500/20 rounded-xl flex items-center gap-3">
                       <RefreshCw size={18} className="text-blue-500 animate-spin-slow"/>
                       <p className="text-[10px] text-gray-400 font-bold uppercase tracking-tight">System automatically maps incoming `click_id` to outbound macros during the relay phase.</p>
                    </div>
                 </div>
              </Card>
           </div>
        )}

        {activeTab === 'affiliate-setup' && (
          <Card title="Partner Global Postback Registry">
             <div className="p-4 mb-6 border-b border-gray-800">
                <div className="relative">
                   <Search className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-600" size={14} />
                   <input type="text" placeholder="Search by Affiliate Name or ID..." className="w-full bg-gray-950 border border-gray-800 rounded-xl pl-9 pr-4 py-2 text-[10px] font-black outline-none focus:ring-1 focus:ring-blue-500" />
                </div>
             </div>
             <div className="overflow-x-auto">
                <table className="w-full text-left">
                   <thead>
                      <tr className="text-[10px] font-black text-gray-600 uppercase tracking-widest border-b border-gray-800 bg-gray-800/30">
                         <th className="p-4">Affiliate</th>
                         <th className="p-4">Postback Configuration</th>
                         <th className="p-4 text-center">Status</th>
                         <th className="p-4 text-right">Action</th>
                      </tr>
                   </thead>
                   <tbody className="divide-y divide-gray-900">
                      <tr className="hover:bg-gray-800/20 transition-colors">
                         <td className="p-4 font-black text-gray-100 uppercase tracking-tight">Elite Performance (AFF-001)</td>
                         <td className="p-4">
                            <code className="text-[9px] text-gray-500 font-mono italic">https://p.aff-node.com/pb?s1={'{click_id}'}&pay={'{payout}'}</code>
                         </td>
                         <td className="p-4 text-center">
                            <span className="text-[9px] font-black uppercase text-green-500 bg-green-500/10 px-2 py-0.5 rounded border border-green-500/20">Verified</span>
                         </td>
                         <td className="p-4 text-right">
                            <button className="text-[9px] font-black uppercase text-blue-400 hover:underline">Edit Node</button>
                         </td>
                      </tr>
                   </tbody>
                </table>
             </div>
          </Card>
        )}
      </div>
    </div>
  );
};

export default Postbacks;